# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - home-loan-predictions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://streamlitcontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7e36ec1d2bcf4392a72a24b1ce54fe66 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d13400d072c24ee4a2149dd1a5d8f05c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: streamlitcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7e36ec1d2bcf4392a72a24b1ce54fe66 }}/sampleapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'home-loan-predictions'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f336ab4bcaa14d35912b433ec19f13a7 }}
        images: 'streamlitcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7e36ec1d2bcf4392a72a24b1ce54fe66 }}/sampleapp:${{ github.sha }}'